### ISSUE TITLE
executeJavaScript always results an empty object as result

### ISSUE THREAD

**Issue by aeneasr** [electron-userland/spectron#163]
Consider this test case:

```jsx
const Application = require('spectron').Application
const path = require('path')
const exec = require('child_process').exec
const electron = path.resolve(__dirname, `../../../node_modules/.bin/electron${process.platform === 'win32' ? '.cmd' : ''}`)

const paths = {
  root: path.join(__dirname, '../../../'),
  main: path.join(__dirname, '../../../src/main/index.js')
}

jasmine.DEFAULT_TIMEOUT_INTERVAL = 30000

let app
const before = () => {
  app = new Application({ path: electron, args: [paths.main] })
  return app.start()
}
const after = () => (app && app.isRunning()) ? app.stop() : null

describe('tests/integration/app', () => {
  describe('window', () => {
    beforeAll(before)
    afterAll(after)

    it('opens a window', () => app.client.waitUntilWindowLoaded())

    it('should run fetch', () => app.webContents.executeJavaScript('fetch("https://jsonplaceholder.typicode.com/users/1").then(resp => resp.json())', true)
      .then((result) => fetch("https://jsonplaceholder.typicode.com/users/1").then((resp) => resp.json()).then((json) => {
        expect(json.id).toEqual(1)
        expect(result).toEqual(json)
      })
    ))
  })
})
```

For some reason, the result is always an empty object:

```
    Expected value to equal:
      {"address": {"city": "Gwenborough", "geo": {"lat": "-37.3159", "lng": "81.1496"}, "street": "Kulas Light", "suite": "Apt. 556", "z
ipcode": "92998-3874"}, "company": {"bs": "harness real-time e-markets", "catchPhrase": "Multi-layered client-server neural-net", "name"
: "Romaguera-Crona"}, "email": "Sincere@april.biz", "id": 1, "name": "Leanne Graham", "phone": "1-770-736-8031 x56442", "username": "Bre
t", "website": "hildegard.org"}

    Received:
      {}
```

Since the example is taken from the official docs, I don't really know what I'm doing wrong here. Any ideas?

**Comment by arekkas** [comment]
I've also tried stuff like `app.webContents.executeJavaScript('"foobar"')` which probably should return `"foobar"`, but got an empty object there as well.

**Comment by arekkas** [comment]
I was able to confirm that this works as expected when used in regular electron. So it has to be something with spectron, I think.

**Comment by MarshallOfSound** [comment]
@arekkas This appears to be due to `webContents.executeJavaScript` returning a promise and we are sending the serialized promise back through spectron not the result of that promise.  Not sure where this can / should be handled

**Comment by arekkas** [comment]
Thank you for tracing that! Not sure I can be of use here :D

**Comment by scottnonnenberg** [comment]
I've noticed that if I have the dev tools open, I can't seem to get the result of javascript snippets like you're doing. Try turning off the dev tools, see what happens!

**Comment by burtonator** [comment]
Ha.. great. just spent 45 minutes of my life debugging this.  Still open after 14 months?  

Any workarounds?  If this bug can't easily be resolved (especially after 14 months) maybe the documentation should at least be opened or have this event throw an exception?

**Comment by burtonator** [comment]
This is a workaround:

        let test = await this.app.client.execute(() => {
            return "hello world";
        });

.. the result actually is its own object with a .value member. The browser documentation in WebDriver doesn't specify this though.
