### ISSUE TITLE
Example of using Spectron for Browser UI automation

### ISSUE THREAD

**Issue by DinisCruz** [electron-userland/spectron#38]
For example:
1) open google
2) enter some text
3) click ok
5) assert search results

This is what I started doing with https://github.com/o2platform/chrome-js which was originally based on NWR, but since Electron really become stable, I have been trying to use it

**Comment by kevinsawicki** [comment]
Are you thinking something like the examples here? http://webdriver.io/#What_is_WebdriverIO_3F

**Comment by DinisCruz** [comment]
yes, but using Spectron instead of Selenium

**Comment by StephenDavidson** [comment]
@DinisCruz I wrote a small one that leverages the browser window, https://github.com/StephenDavidson/electron-spectron-example let me know if that helps

**Comment by Gill-Heron** [comment]
Would it be possible to configure and run Spectron from something like Karma? My searches for examples are coming up empty. We're using Spectron and raw Jasmine at the moment (with several helper packages) and would benefit from the consolidated configuration and plugin architecture of Karma or similar.

**Comment by StephenDavidson** [comment]
https://github.com/bensu/doo/issues/90

**Comment by amilajack** [comment]
You should use [nightmare](https://github.com/segmentio/nightmare) for this
