### ISSUE TITLE
[feature request] Electron 6 support

### ISSUE THREAD

**Issue by vladimiry** [electron-userland/spectron#404]
I tried making Spectron use electron-chromedriver@6.0.0 but it still fails with "ChromeDriver did not start within 5000ms" error message.

**Comment by HaNdTriX** [comment]
I have a similar issue when using electron@6


```js
const app = new Application({
   ...
})

await app.start() // <-- This call never resolves even though the app starts
```

**Comment by vladimiry** [comment]
> I just realized that spectron@5 is working fine with electron@6

Still doesn't work for me.

The error I get (at least it got connected with chrome driver):
```
node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143
  Rejected promise returned by test. Reason:
  Error {
    details: undefined,
    message: 'Client initialization failed after 1 attempts: RuntimeError Client initialization failed after 1 attempts: ',
    seleniumStack: {
      message: 'A new session could not be created.',
      orgStatusMessage: `session not created: Chrome version must be between 70 and 73␊
        (Driver info: chromedriver=2.45 (7154f3777129c2f32d160297120b6e200ec29830),platform=Linux 5.2.4-1-MANJARO x86_64)`,
      type: 'SessionNotCreatedException',
    },
    type: 'RuntimeError',
  }
  new RuntimeError (node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143:12)
  Request._callback (node_modules/webdriverio/build/lib/utils/RequestHandler.js:318:39)
  Request.self.callback (node_modules/request/request.js:185:22)
  Request.<anonymous> (node_modules/request/request.js:1161:10)
  IncomingMessage.<anonymous> (node_modules/request/request.js:1083:12)
```

`node ./node_modules/electron-chromedriver/chromedriver.js -v` output:
```
ChromeDriver 2.45 (7154f3777129c2f32d160297120b6e200ec29830)
```

And I get the following error when I make Spectron use electron-chromedriver@6.0.0:
```
  Error {
    message: 'ChromeDriver did not start within 5000ms',
  }
  node_modules/spectron/lib/chrome-driver.js:63:25
  Request._callback (node_modules/spectron/lib/chrome-driver.js:123:5)
```

`node ./node_modules/electron-chromedriver/chromedriver.js -v` output:
```
ChromeDriver 76.0.3809.88 (e67b7e2f345cbedc6a24e0074a1a528c724f5915-refs/branch-heads/3809@{#968})
```

**Comment by HaNdTriX** [comment]
@vladimiry I had a similar issue. I resolved it by reinstalling my node_modules.

```js
rm -rf node_modules && npm install
```

**Comment by vladimiry** [comment]
I tried reinstalling the modules of course including removing the lock file but the error is the same:
```
node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143
...
    seleniumStack: {
      message: 'A new session could not be created.',
      orgStatusMessage: `session not created: Chrome version must be between 70 and 73␊
```

To be clear, the app starts and I can see the expected screen but since selenium responds with the error the testing process doesn't go further.

**Comment by vladimiry** [comment]
Got it working on least my case with chromedriver ^76. It requires making spectron use electron-chromedriver@6.0.0 and minor code change since `/wd/hub/status` endpoint response format got changed with `chromedriver 2.45 => 76.0.3809.88` version update.

**Comment by vladimiry** [comment]
PR is open, #406.

**Comment by TiagoDanin** [comment]
sentiram saudades?

estava dando um tempo para rede sociais para forca em coisa mais uteis

**Comment by vladimiry** [comment]
Actually there was already open [PR](https://github.com/electron-userland/spectron/pull/373) which I didn't notice, so closing mine and the issue.
