### ISSUE TITLE
Error: session not created: This version of ChromeDriver only supports Chrome version 76

### ISSUE THREAD

**Issue by Ankitr19** [electron-userland/spectron#430]
Hi all, I am getting this error when I am trying to run the test. And also my chrome version is 76.0.3809.132 , any idea why this is occurring?

**Comment by Ankitr19** [comment]
Resolved : I was using the wrong electron and spectron versions

**Comment by jake-harris** [comment]
Thanks for posting the follow-up, @Ankitr19. Made me realize I was doing the same.

**Comment by sowmyamurukutla** [comment]
@Ankitr19 where can we find the list of compatible versions of spectron for corresponding electron version

**Comment by Ankitr19** [comment]
@sowmyamurukutla its present in the readme section here https://github.com/electron-userland/spectron
