### ISSUE TITLE
Move @types/webdriverio from devDependencies to dependencies

### ISSUE THREAD

**Issue by Toromyx** [electron-userland/spectron#497]
The Spectron declaration file [spectron.d.ts](https://github.com/electron-userland/spectron/blob/master/lib/spectron.d.ts) depends on types from `@types/webdriverio`.

In a Typescript project depending on spectron, typescript throws the error
```
node_modules/spectron/lib/spectron.d.ts(9,34): error TS7016: Could not find a declaration file for module 'webdriverio'. '-------/node_modules/webdriverio/build/index.js' implicitly has an 'any' type.
[typescript]   Try `npm install @types/webdriverio` if it exists or add a new declaration (.d.ts) file containing `declare module 'webdriverio';`
```
This is because `@types/webdriverio` is defined as devDependency and therefore not installed in projects depending on `spectron`.

A simple workaround is to install `@types/webdriverio` yourself. This is not a permament solution because for every new version of `spectron` you have to check if your defined version of `@types/webdriverio` still fits.

**Comment by vladimiry** [comment]
Please don't as @types/webdriverio is not a runtime/production dependency. Installing declarations is up to the developer.

**Comment by Toromyx** [comment]
> Please don't as @types/webdriverio is not a runtime/production dependency. Installing declarations is up to the developer.

Internally Spectron uses a specific version of `webdriverio` as well as `@types/webdriverio`, I would argue it is not up to the consuming developer to make sure their installed version is compatible. Read more [in this microsoft/type-publisher issue](https://github.com/microsoft/types-publisher/issues/81).

You are right, it is not a runtime dependency, but it could be argued that it is a production dependency: [spectron.d.ts](https://github.com/electron-userland/spectron/blob/master/lib/spectron.d.ts) is part of the productive Spectron node module, it depends on `@types/webdriverio`, therefore `@types/webdriverio` should also be part of the productive node module.

**Comment by vladimiry** [comment]
I think I overlooked this, you are right It would be more convenient for the built-in declaration/spectron.d.ts to be paired with pinned @types/webdriverio version when I install the spectron package from npm repository (for example right now it's unsafe to use @types/webdriverio@5 since it's not yet supported by spectron).
