### ISSUE TITLE
Error :   TypeError: waitUntilWindowLoaded Cannot read property 'isLoading' of undefined when calling app.client.waitUntilWindowLoaded()

### ISSUE THREAD

**Issue by BabuShoban** [electron-userland/spectron#570]
I am using electron version "6.1.9" and spectron "8.0.0" , node integration in my electron app is set to "true"

I am rendering a website inside "webview" tag and I want to test some component on the web site which is inside "webview" tag

When I run app.client.getwindowcount() , I see it returning window count as 2. Below is the code snippet which is failing.

Code Snippet:
  
  `await app.client.windowByIndex(1)
  await app.client.waitUntilWindowLoaded()`

Below are the web preferences set inside my electron application:

`webPreferences: {
		nativeWindowOpen: false,
		nodeIntegration: true,
		contextIsolation: true,
		webviewTag: true,
		enableRemoteModule: false,
		preload: path.join(__dirname, ".//", "preload.js")
	} `

Please help me with this issue.

**Comment by sarathms** [comment]
Getting started with Spectron, this was one of the many things that frustrated me. I don't recall which one solved this particular problem, but you may try these:
1. Make sure you avoid opening devTools. I use `cross-env NODE_env=test mocha` in `package.json` and then use it in `main.js` to skip opening devTools and extensions.

2. If you are developing on Linux, run this command once per desktop session. This seems to be needed for newer versions of `electron`
````
sudo sysctl kernel.unprivileged_userns_clone=1
````

**Comment by BabuShoban** [comment]
@sarathms  Thanks for taking time to reply on this issue.

The above solution will not work for me as I have not added code to open dev tools or extensions. Also, I am running the test on windows OS.

**Comment by pcawen** [comment]
Having the same issue here, The problem seems to be related to ```contextIsolation: true,``` if you set it to false it works but you can't use contextBridge on your preload.js since contextBridge require contextIsolation to be true.

If you log the value of app.electron with ```contextIsolation: true,``` it is undefined but with  ```contextIsolation: false,``` it contains an object.

I try adding this line to preload. js without luck
```contextBridge.exposeInMainWorld('electronRequire', require);```

**Comment by shadow-light** [comment]
Looks like Electron needs significant changes to fix this: https://github.com/electron-userland/spectron/issues/896#issuecomment-881900473
