### ISSUE TITLE
broken my chaining test with waitForVisible()

### ISSUE THREAD

**Issue by MichinariNukazawa** [electron-userland/spectron#663]
I need access input element in spectron test.
and need fix broken my test.

Why nothing to basic element test example?
(I know WebDriver test example not working in spectron.
  - synchronous code not runnable in spectron.
  - need replace `$(ID)` -> `this.app.client.$$(ID)`)

(stackoverflow codes is old and not working...)

I use code of test to test:
(write to input elemet, and read from input element.)
```
	it("input basic test", function() {
		return this.app.client.waitForVisible('#query-area__query-input__input')
				.waitForEnabled('#query-area__query-input__input')
				.clearElement('#query-area__query-input__input')
				.setValue('#query-area__query-input__input', "Bonan matenon!")
				.getValue('#query-area__query-input__input')
				.then(function(text){assert(text === 'Bonan matenon!')})
	})
```
in https://github.com/MichinariNukazawa/lina_dicto/blob/master/lina_dicto/test/input_ui.js

upon error when npm update.
spectron: 11.0.0 -> 11.1.0, electron: 9.0.4 -> 9.1.1
error: `TypeError: this.app.client.waitForVisible is not a function`

because from waitForVisible() is deprecated (?).
https://stackoverflow.com/questions/59949831/non-of-the-webdriverio-methods-work-to-wait-until-an-element-is-shown-using-appi
Okay I do use waitForDisplayed.

but simple replace is not working.
```
-               return this.app.client.waitForVisible('#query-area__query-input__input')
+               return this.app.client.waitForDisplayed('#query-area__query-input__input')
```
error: `TypeError: this.app.client.waitForDisplayed is not a function`

> waitForDisplayed() and isDisplayed() are not functions of this.app.client
https://github.com/electron-userland/spectron/issues/355

**Comment by harrellbm** [comment]
I am getting a similar error:

```
 TypeError: app.client.click is not a function
      at Context.<anonymous> (test/test_index.js:598:22)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Click seems to still be in the new webdriver documentation.  So I am confused.

**Comment by xasopheno** [comment]
Same

**Comment by mtriff** [comment]
Webdriver made major changes to their API with v5. Unfortunately, it isn't a direct replacement. See their release notes for their upgrade guide: https://github.com/webdriverio/webdriverio/blob/f759ba10fcd951e1622844de9b0943eb6cc6f14f/CHANGELOG.md#v500-2018-12-20

You'll need to change to something like:
```
app.client.$('#query-area__query-input__input').waitForDisplayed();
```

**Comment by MichinariNukazawa** [comment]
Thanks for you reply.
But did not solve the problem.

code:
`		return this.app.client.$('#query-area__query-input__input').waitForDisplayed();`
result:
```
input basic test:
     TypeError: this.app.client.$(...).waitForDisplayed is not a function
      at Context.<anonymous> (test/input_ui.js:26:63)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

----
other info
debug printing:
`console.log("AA", this.app.client.$('#query-area__query-input__input'))`
console output to:
`AA Promise { <pending> }`

**Comment by mtriff** [comment]
You need to await the appropriate values, i.e.
```
return (await this.app.client.$('#query-area__query-input__input')).waitForDisplayed();
```

Or, to get the result:

```
let isDisplayed = await (await this.app.client.$('#query-area__query-input__input')).waitForDisplayed();
```

**Comment by MichinariNukazawa** [comment]
Success able call waitForDisplayed().
Thanks!
