### ISSUE TITLE
Support for Electron v11

### ISSUE THREAD

**Issue by panther7** [electron-userland/spectron#770]
> Error: Failed to create session.
> session not created: This version of ChromeDriver only supports Chrome version 85
>      at Object.startWebDriverSession (node_modules\webdriver\build\utils.js:34:15)
>      at processTicksAndRejections (node:internal/process/task_queues:93:5)
>      at async Function.newSession (node_modules\webdriver\build\index.js:30:45)
>      at async Object.exports.remote (node_modules\webdriverio\build\index.js:60:22)

**Comment by VerteDinde** [comment]
Hey @panther7! We're working on the release of 11 now, should be merged and published today. I'll close this when it's released.

**Comment by panther7** [comment]
Is possible releases beta for electron@beta channel? Thanks

**Comment by jehon** [comment]
The PR has been merged... (thanks a lot for this work)!
What about releasing a beta as proposed by @panther7  ?

**Comment by twitharshil** [comment]
@VerteDinde Any timelines for having a spectron release that supports electron v11 ?

**Comment by kevinlinv** [comment]
Hi @VerteDinde 👋, I think people are keen to upgrade to Electron 11 to unlock the ability to ship Apple Silicon Support of their apps. Which at present would be blocked on Spectron if their end to end tests are important in the release cycle.

Would it be possible to provide some timeline on when we're planning on a new release of Spectron with Electron 11 support? Thanks!

**Comment by jehon** [comment]
Hello,
In the meantime, you can use github as a package source:

`npm install --save-dev "electron-userland/spectron"`

Please a sticky note somewhere to go back to normal when this is released...

**Comment by kevinlinv** [comment]
Thanks for posting the workaround @jehon Appreciate it 🙏 Shall try that!

**Comment by VerteDinde** [comment]
@kevinlinv @panther7 Just wanted to send you both a direct ping - a new version of Spectron was just published, v13.0.0, for Electron 11. If you have any issues upgrading, let us know! I'll close this issue and we can open new issues for v13 specifically as needed.

**Comment by kevinlinv** [comment]
🙌 thanks for the ping! 🎉

**Comment by panther7** [comment]
Thanks, I [said before](https://github.com/electron-userland/spectron/issues/770#issuecomment-730517177), is possible releasing spectron for beta channel electron too? @VerteDinde
