### ISSUE TITLE
Electron 11: Methods on `remote.screen` are not defined

### ISSUE THREAD

**Issue by VerteDinde** [electron-userland/spectron#771]
Note: Spectron currently depends on the remote module, and will need to be rewritten not to depend on remote to match Electron's main repo. We're currently looking for help from folks who may be interested in helping with this initiative - if you might be interested, please let us know!

Beginning in Electron 11, the screen module in both the main process and the remote module is now exported as a proxy, which lazily calls createScreen on first access. This proxy does not seem to be loading properly in the remote module, and is causing an error with remote's screen API methods.

This is a known issue within remote only; calling `screen` methods from the main process works as expected.

**Comment by andersk** [comment]
Shouldn’t this be filed in electron/electron?

**Comment by andersk** [comment]
Filed upstream as electron/electron#26610.

**Comment by VerteDinde** [comment]
@andersk Thanks for filing that! We're on a path to deprecating the remote module in the main Electron repo ([more information in this issue here](https://github.com/electron/electron/issues/21408)). I'll keep this issue open until we're able to rewrite Spectron so it doesn't depend on remote 🙂

**Comment by andersk** [comment]
My fix for the `remote.screen` issue was backported in Electron 11.0.3, just released.

**Comment by deanylev** [comment]
It seems like the EventEmitter methods like `on` are still undefined in this scenario? Testing on 11.0.3

**Comment by andersk** [comment]
@deanylev You seem to be correct, but reporting this on a closed issue in the wrong repository isn’t likely to do much good—file an issue in electron/electron.

**Comment by VerteDinde** [comment]
@deanylev Just triaged your bug in the electron/electron repo, we'll see if we can add a fix
