### ISSUE TITLE
How use spectron to test mobile application

### ISSUE THREAD

**Issue by kurtyczanka** [electron-userland/spectron#845]
How are you using Spectron to test mobile applications? I'm using Spectron to test a desktop app and it works nice. Now I want to run this test on mobile devices (android and ios). I can write tests in webdriverIO and run it in Appium, but I want to reuse some tests from desktop. How can I achieve it?

**Comment by VerteDinde** [comment]
Hey @kurtyczanka! At this time, Spectron is desktop-only, as Electron itself only supports desktop apps. You may be able to port some of the tests over to use just Webdriver. Best of luck with your mobile app!
